- hosts: masters
  become: yes
  tasks:
   - name: Clone rook source
     git:
       repo: 'https://github.com/rook/rook.git'
       single_branch: yes
       dest: /root/rook
       version: release-1.10

   - name: Install ceph cluster
     shell: |
       kubectl apply -f rook/deploy/examples/crds.yaml
       kubectl apply -f rook/deploy/examples/common.yaml
       kubectl apply -f rook/deploy/examples/operator.yaml
       kubectl apply -f rook/deploy/examples/cluster.yaml
       kubectl apply -f rook/deploy/examples/filesystem.yaml
       kubectl apply -f rook/deploy/examples/csi/cephfs/storageclass.yaml
       kubectl apply -f rook/deploy/examples/dashboard-external-https.yaml
       kubectl apply -f rook/deploy/examples/toolbox.yaml
