apiVersion: v1
kind: Service
metadata:
  name: tmax-grafana-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector:
    app: tmax-grafana
  ports:
    - port: 3000
