apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tmax-redmine-ingress
  namespace: osinfra
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 300m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: redmine.tmaxos.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tmax-redmine-service
            port:
              number: 3000

---

kind: Service
apiVersion: v1
metadata:
  name: tmax-redmine-service
  namespace: osinfra
spec:
  type: NodePort
  selector:
    app: tmax-redmine
  ports:
    - port: 3000 # Default port for image
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tmax-redmine-pvc
  namespace: osinfra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmax-redmine-pv
  namespace: osinfra
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.135
    path: /home/share/tmax-nfs/tmax-redmine

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmax-redmine
  namespace: osinfra
spec:
  selector:
    matchLabels:
      app: tmax-redmine
  replicas: 1
  template:
    metadata:
      labels:
        app: tmax-redmine
    spec:
      containers:
      - name: tmax-redmine
        image: redmine:4.2.3
        resources:
          requests:
            memory: "2Gi"
            cpu: 2
          limits:
            memory: "2Gi"
            cpu: 2
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /usr/src/redmine/files
          name: tmax-redmine-volume
          subPath: files
        - mountPath: /usr/src/redmine/plugins
          name: tmax-redmine-volume
          subPath: plugins
        - mountPath: /usr/src/redmine/public/themes
          name: tmax-redmine-volume
          subPath: themes
        env:
        - name: REDMINE_DB_MYSQL
          value: 127.0.0.1
        - name: REDMINE_DB_DATABASE
          value: redmine_default
        - name: REDMINE_DB_USERNAME
          value: root
        - name: REDMINE_DB_PASSWORD
          value: tmax123
        - name: REDMINE_PLUGINS_MIGRATE
          value: "true"
        - name: REDMINE_SECRET_KEY_BASE
          value: supersecretkey
      - name: tmax-redmine-db
        image: mariadb
        resources:
          requests:
            memory: "2Gi"
            cpu: 2
          limits:
            memory: "2Gi"
            cpu: 2
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: tmax-redmine-volume
          subPath: data
        - mountPath: /etc/mysql/conf.d
          name: tmax-redmine-volume
          subPath: conf
        env:
        - name: MYSQL_DATABASE
          value: redmine_default
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: tmax123
        - name: MYSQL_ROOT_PASSWORD
          value: tmax123
      volumes:
      - name: tmax-redmine-volume
        persistentVolumeClaim:
          claimName: tmax-redmine-pvc
