apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmax-prometheus-pv
  namespace: monitoring
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.135
    path: /home/share/tmax-nfs/tmax-prometheus
