apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tmax-b2b-repo-ingress
  namespace: osinfra
spec:
  ingressClassName: nginx
  rules:
  - host: b2b-repo.tmaxos.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tmax-b2b-repo-service
            port:
              number: 80
  - host: b2b-ci.tmaxos.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tmax-b2b-repo-service
            port:
              number: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: tmax-b2b-repo-service
  namespace: osinfra
spec:
  type: NodePort
  selector:
    app: tmax-b2b-repo
  ports:
    - name: nginx
      protocol: TCP
      port: 80 # Default port for image
    - name: jenkins
      protocol: TCP
      port: 8080 # Default port for image

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmax-b2b-repo-pv
  namespace: osinfra
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.135
    path: /home/share/tmax-nfs/tmax-b2b-repo

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tmax-b2b-repo-pvc
  namespace: osinfra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmax-b2b-repo
  namespace: osinfra
spec:
  selector:
    matchLabels:
      app: tmax-b2b-repo
  replicas: 1
  template:
    metadata:
      labels:
        app: tmax-b2b-repo
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: tmax-b2b-repo
        image: harbor.tmaxos.net/infra/b2b-repo:1.0.1
        resources:
          requests:
            memory: "2Gi"
            cpu: 1
          limits:
            memory: "2Gi"
            cpu: 1
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/spool/aptly
          name: tmax-b2b-repo-volume
          subPath: aptly
      - name: tmax-b2b-ci
        image: jenkins/jenkins:lts
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "2Gi"
            cpu: 1
          limits:
            memory: "2Gi"
            cpu: 1
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: tmax-b2b-repo-volume
          subPath: jenkins
      volumes:
      - name: tmax-b2b-repo-volume
        persistentVolumeClaim:
          claimName: tmax-b2b-repo-pvc
