kind: ConfigMap
apiVersion: v1
metadata:
  name: tmax-logstash-configmap
  namespace: tmaxos-infra
data:
  logstash.conf: >-
    input { kafka { bootstrap_servers => "http://tmax-kafka-service:9092" topics
    => "test" enable_auto_commit => "true" auto_offset_reset => "latest" codec
    => "json" } } output { elasticsearch { hosts =>
    ["http://tmax-elasticsearch-service:9200"] manage_template => false index =>
    "test-log-%{+YYYY-MM-dd}" } }
  logstash.yml: |
    http.host: "127.0.0.0"
    path.config: /usr/share/logstash/pipeline

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: tmax-logstash
  namespace: tmaxos-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmax-logstash
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tmax-logstash
    spec:
      volumes:
        - name: logstash-config-volume
          configMap:
            name: tmax-logstash-configmap
            items:
              - key: logstash.yml
                path: logstash.yml
            defaultMode: 420
        - name: logstash-pipeline-volume
          configMap:
            name: tmax-logstash-configmap
            items:
              - key: logstash.conf
                path: logstash.conf
            defaultMode: 420
      containers:
        - name: tmax-logstash
          image: 'docker.elastic.co/logstash/logstash:7.15.2'
          ports:
            - containerPort: 5044
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          volumeMounts:
            - name: logstash-config-volume
              mountPath: /usr/share/logstash/config
            - name: logstash-pipeline-volume
              mountPath: /usr/share/logstash/pipeline
