kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: tmax-kibana-ingress
  namespace: tmaxos-infra
  annotations:
    kubernetes.io/ingress.class: nginx-shd
spec:
  rules:
    - host: ${KIBANA DOMAIN NAME} 
      http:
        paths:
          - path: /
            backend:
              serviceName: tmax-kibana-service
              servicePort: 5601
---

kind: Service
apiVersion: v1
metadata:
  name: tmax-kibana-service
  namespace: tmaxos-infra
spec:
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  selector:
    app: tmax-kibana

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: tmax-kibana
  namespace: tmaxos-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmax-kibana
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tmax-kibana
    spec:
      containers:
        - name: tmax-kibana
          image: 'docker.elastic.co/kibana/kibana:7.15.2'
          ports:
            - name: external
              containerPort: 5601
              protocol: TCP
          env:
            - name: SERVER_NAME
              value: tmax-kibana
            - name: ELASTICSEARCH_HOSTS
              value: 'http://tmax-elasticsearch-service:9200'
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
