apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tmax-wiki-ingress
  namespace: osinfra
spec:
  ingressClassName: nginx
  rules:
  - host: wiki.tmaxos.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tmax-wiki-service
            port:
              number: 80

---

kind: Service
apiVersion: v1
metadata:
  name: tmax-wiki-service
  namespace: osinfra
spec:
  selector:
    app: tmax-wiki
    #  type: LoadBalancer
  ports:
    - port: 80 # Default port for image

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tmax-wiki-pvc
  namespace: osinfra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmax-wiki-pv
  namespace: osinfra
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.135
    path: /home/share/tmax-nfs/tmax-wiki

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmax-wiki
  namespace: osinfra
spec:
  selector:
    matchLabels:
      app: tmax-wiki
  replicas: 1
  template:
    metadata:
      labels:
        app: tmax-wiki
    spec:
      containers:
      - name: tmax-wiki
        image: mediawiki:1.37.1
        resources:
          requests:
            memory: "128Mi"
            cpu: 0.5 
          limits:
            memory: "128Mi"
            cpu: 0.5
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/images
          name: tmax-wiki-volume
          subPath: images
        - mountPath: /var/www/html/skins
          name: tmax-wiki-volume
          subPath: skins
        - mountPath: /var/www/html/LocalSettings.php
          name: tmax-wiki-volume
          subPath: LocalSettings.php
      - name: tmax-wiki-db
        image: mariadb
        resources:
          requests:
            memory: "128Mi"
            cpu: 0.5
          limits:
            memory: "128Mi"
            cpu: 0.5
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: tmax-wiki-volume
          subPath: data
        env:
        - name: MYSQL_DATABASE
          value: gk_wiki
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: tmax123
        - name: MYSQL_ROOT_PASSWORD
          value: tmax123
      volumes:
      - name: tmax-wiki-volume
        persistentVolumeClaim:
          claimName: tmax-wiki-pvc
